---
name: Workflow Environment
on:
  workflow_dispatch:

jobs:
  test_scripts:
    name: Test Scripts
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      # These stage versions are pinned by https://github.com/renovatebot/renovate
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Run Test Script
        run:
          ./test_script.sh
